"""empty message

Revision ID: 2b713045e1a2
Revises: 6ab0da78b291
Create Date: 2025-05-22 18:16:49.901471

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b713045e1a2"
down_revision = "6ab0da78b291"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("hire_statistics_country_code_key"), "hire_statistics", type_="unique"
    )
    op.drop_constraint(
        op.f("hire_statistics_standard_job_id_key"), "hire_statistics", type_="unique"
    )
    op.create_unique_constraint(
        "uq_hire_statistics_stdjob_country",
        "hire_statistics",
        ["standard_job_id", "country_code"],
        schema="public",
    )
    op.drop_constraint(
        op.f("hire_statistics_standard_job_id_fkey"),
        "hire_statistics",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "hire_statistics",
        "standard_job",
        ["standard_job_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hire_statistics", schema="public", type_="foreignkey")
    op.create_foreign_key(
        op.f("hire_statistics_standard_job_id_fkey"),
        "hire_statistics",
        "standard_job",
        ["standard_job_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_hire_statistics_stdjob_country",
        "hire_statistics",
        schema="public",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("hire_statistics_standard_job_id_key"),
        "hire_statistics",
        ["standard_job_id"],
    )
    op.create_unique_constraint(
        op.f("hire_statistics_country_code_key"), "hire_statistics", ["country_code"]
    )
    # ### end Alembic commands ###
