"""empty message

Revision ID: 3911b0cf0755
Revises: 2b713045e1a2
Create Date: 2025-05-23 03:45:43.625380

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3911b0cf0755"
down_revision = "2b713045e1a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hire_statistics",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "hire_statistics",
        sa.Column("threshold", sa.Integer(), server_default="5", nullable=True),
    )
    op.drop_constraint(
        op.f("hire_statistics_standard_job_id_fkey"),
        "hire_statistics",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "hire_statistics",
        "standard_job",
        ["standard_job_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hire_statistics", schema="public", type_="foreignkey")
    op.create_foreign_key(
        op.f("hire_statistics_standard_job_id_fkey"),
        "hire_statistics",
        "standard_job",
        ["standard_job_id"],
        ["id"],
    )
    op.drop_column("hire_statistics", "threshold")
    op.drop_column("hire_statistics", "updated_at")
    # ### end Alembic commands ###
