"""empty message

Revision ID: 6ab0da78b291
Revises: 96379826d88c
Create Date: 2025-05-22 17:51:25.410807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab0da78b291'
down_revision = '96379826d88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hire_statistics', ['standard_job_id'], schema='public')
    op.create_unique_constraint(None, 'hire_statistics', ['country_code'], schema='public')
    op.drop_constraint(op.f('hire_statistics_standard_job_id_fkey'), 'hire_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'hire_statistics', 'standard_job', ['standard_job_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hire_statistics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('hire_statistics_standard_job_id_fkey'), 'hire_statistics', 'standard_job', ['standard_job_id'], ['id'])
    op.drop_constraint(None, 'hire_statistics', schema='public', type_='unique')
    op.drop_constraint(None, 'hire_statistics', schema='public', type_='unique')
    # ### end Alembic commands ###
