"""empty message

Revision ID: 96379826d88c
Revises: 5f9f370fb3d9
Create Date: 2025-05-22 03:28:08.825796

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96379826d88c"
down_revision = "5f9f370fb3d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "hire_statistics",
        "standard_job",
        ["standard_job_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hire_statistics", schema="public", type_="foreignkey")
    # ### end Alembic commands ###
